### ISSUE TITLE
Let there be light!

### ISSUE THREAD

**Issue by YankaPt** [repometric/lhexec#1]
And let there be a vault between the waters to separate water from water!

**Comment by YankaPt** [comment]
And let the water under the sky be gathered to one place, and let dry ground appear!

**Comment by xferra** [comment]
[![CLICK ME](https://user-images.githubusercontent.com/674129/39075143-fdb8e93e-44fc-11e8-97e6-1275c2ec8f2f.jpg)](https://www.youtube.com/embed/Sagg08DrO5U)
